lidar_extrinsics:
  # Vehicle has body frame and lidar has livox_frame
  # Body frame: X forward, Y left, Z up
  # Livox frame: X forward, Y right, Z up
  lidar_frame: "livox_frame"
  vehicle_frame: "body"
  # Parameters from lidar frame to vehicle frame
  x_lidar_vehicle: 0.0 # meters
  y_lidar_vehicle: 0.0 # meters
  z_lidar_vehicle: 0.0 # meters
  roll_lidar_vehicle: 180.0 # degrees
  pitch_lidar_vehicle: 0.0 # degrees
  yaw_lidar_vehicle: 0.0 # degrees

# Vehicle dimensions in vehicle frame that should be filtered out
vehicle_region_box:
  width: 0.60 # meters
  length: 0.60 # meters
  height: 0.90 # meters
  